// Preloads a large set of real, researched flood-prone and pothole hotspots
// across ~30 Indian cities, so the map has meaningful nationwide coverage
// beyond Mumbai on day one. This was compiled externally (news reporting,
// municipal corporation lists — BMC, BBMP, GHMC, PWD, etc. — see each
// entry's own "Source:" line in its notes) and imported here as a one-time
// seed, the same way seed/potholes.js preloads Mumbai pothole spots.
//
// IMPORTANT: several entries' own notes flag that the underlying source is
// several years old or "not confirmed current" — that caveat is preserved
// in the notes text itself, so read an entry's notes before treating it as
// up to date.
//
// Run with:  node seed/nationwide.js
// Safe to re-run — it upserts on (type + rounded lat/lng) instead of
// duplicating entries every time, exactly like seed/potholes.js.

import dotenv from "dotenv";
import mongoose from "mongoose";
import { connectDB } from "../config/db.js";
import Report from "../models/Report.js";

dotenv.config();

const NATIONWIDE_SEED = [
  { areaName: `Hindmata Circle, Dadar`, lat: 19.0096562, lng: 72.8415602, severity: "impassable", type: "waterlogging", notes: `Status: BMC-identified chronic flood-prone spot — one of 386 originally flagged citywide | Note: BMC widened drains and built an underground water-storage tank here as part of a Rs 150 crore mitigation budget (2021-22), but the junction still floods within minutes of heavy rain and can take hours to drain | Source: BMC 2026 monsoon flood-spot list; Free Press Journal, Feb 2021` },
  { areaName: `Milan Subway, Andheri`, lat: 19.0904131, lng: 72.8430931, severity: "impassable", type: "waterlogging", notes: `Status: BMC-identified chronic flood-prone spot | Note: Underground water-storage tank installed, but the subway has been closed to traffic for a full day at a time (overnight into next afternoon) during first heavy monsoon spells | Source: BMC 2026 monsoon flood-spot list; Hindustan Times, July 2022` },
  { areaName: `Andheri Subway`, lat: 19.1242067, lng: 72.8473323, severity: "impassable", type: "waterlogging", notes: `Status: BMC-identified chronic flood-prone spot, part of the Andheri–Lokhandwala–Oshiwara cluster that residents describe as flooding almost every heavy spell | Note: Water level under the subway has risen high enough to make it risky for vehicles to pass | Source: Hindustan Times, July 2022; June 2026 reporting` },
  { areaName: `Sion Circle`, lat: 19.0426668, lng: 72.8635441, severity: "difficult", type: "waterlogging", notes: `Status: BMC-identified chronic flood-prone spot | Source: BMC 2026 monsoon flood-spot list, via news reporting` },
  { areaName: `Kurla West`, lat: 19.0707532, lng: 72.8781322, severity: "minor", type: "waterlogging", notes: `Status: BMC-identified chronic flood-prone spot | Source: BMC 2026 monsoon flood-spot list, via news reporting` },
  { areaName: `Dadar TT (Tilak Bridge)`, lat: 19.0198787, lng: 72.8447357, severity: "clear", type: "waterlogging", notes: `Status: BMC-identified chronic flood-prone spot | Source: BMC 2026 monsoon flood-spot list, via news reporting` },
  { areaName: `King's Circle, Matunga`, lat: 19.0327753, lng: 72.8561072, severity: "difficult", type: "waterlogging", notes: `Status: Waterlogging reported during July 2026 heavy-rain spell | Source: news reporting, July 2026` },
  { areaName: `Gandhi Market, Sion`, lat: 19.0315155, lng: 72.8587135, severity: "difficult", type: "waterlogging", notes: `Status: Waterlogging reported during July 2026 heavy-rain spell | Source: news reporting, July 2026` },
  { areaName: `Churchgate`, lat: 18.9322453, lng: 72.8264378, severity: "minor", type: "waterlogging", notes: `Status: Newly added to BMC's 2026 flood-prone list (South Mumbai) | Source: BMC 2026 monsoon flood-spot list, via news reporting` },
  { areaName: `Kemps Corner`, lat: 18.9629177, lng: 72.8053877, severity: "minor", type: "waterlogging", notes: `Status: Newly added to BMC's 2026 flood-prone list (South Mumbai) | Source: BMC 2026 monsoon flood-spot list, via news reporting` },
  { areaName: `Oval Maidan`, lat: 18.9296227, lng: 72.8288877, severity: "minor", type: "waterlogging", notes: `Status: Newly added to BMC's 2026 flood-prone list (South Mumbai) | Source: BMC 2026 monsoon flood-spot list, via news reporting` },
  { areaName: `Hutatma Chowk (Flora Fountain)`, lat: 18.9324806, lng: 72.8315166, severity: "minor", type: "waterlogging", notes: `Status: Added to BMC's 2026 flood-prone list after prior year's heavy waterlogging | Source: Indian Express / BMC 2026 monsoon flood-spot list` },
  { areaName: `Cuffe Parade`, lat: 18.9126831, lng: 72.8212934, severity: "clear", type: "waterlogging", notes: `Status: Waterlogging reported during first heavy monsoon spells | Source: news reporting` },
  { areaName: `Worli`, lat: 18.9986406, lng: 72.8173599, severity: "clear", type: "waterlogging", notes: `Status: Waterlogging reported during first heavy monsoon spells | Source: news reporting` },
  { areaName: `Malad Subway`, lat: 19.1893704, lng: 72.8492064, severity: "impassable", type: "waterlogging", notes: `Status: Chronic subway closure spot in heavy rain | Source: news reporting` },
  { areaName: `Dahisar Subway`, lat: 19.2559558, lng: 72.8589312, severity: "impassable", type: "waterlogging", notes: `Status: Chronic subway closure spot in heavy rain | Source: news reporting` },
  { areaName: `Khar Subway`, lat: 19.0752002, lng: 72.8411544, severity: "difficult", type: "waterlogging", notes: `Status: Chronic subway closure spot in heavy rain | Source: news reporting` },
  { areaName: `Vakola Nullah area, Santacruz East`, lat: 19.0801715, lng: 72.8495237, severity: "difficult", type: "waterlogging", notes: `Status: Low-lying area along nullah bank; history of monsoon-related structural incidents | Source: news reporting` },
  { areaName: `Lokhandwala–Oshiwara, Andheri West`, lat: 19.1435906, lng: 72.8246291, severity: "difficult", type: "waterlogging", notes: `Status: Chronic waterlogging pocket in western suburbs | Source: news reporting` },
  { areaName: `S.V. Road, Bandra–Dahisar stretch`, lat: 19.1393739, lng: 72.8443631, severity: "difficult", type: "waterlogging", notes: `Status: Water stagnation reported along this corridor in heavy rain | Note: Metro construction work along this stretch has been blamed for worsening drainage, as dug-up sections trap rainwater | Source: Hindustan Times, July 2022` },
  { areaName: `Wadala`, lat: 19.0148695, lng: 72.863143, severity: "difficult", type: "waterlogging", notes: `Status: Chronic flood-prone spot, low-lying rail-adjacent area | Source: news reporting` },
  { areaName: `Chunabhatti`, lat: 19.0516931, lng: 72.8691602, severity: "difficult", type: "waterlogging", notes: `Status: Chronic flood-prone spot near rail line | Source: news reporting` },
  { areaName: `Parel`, lat: 19.0035047, lng: 72.8418388, severity: "difficult", type: "waterlogging", notes: `Status: Chronic flood-prone spot, BMC budget allocation for mitigation works | Source: news reporting` },
  { areaName: `Sion Road No. 24`, lat: 19.0318907, lng: 72.8596559, severity: "difficult", type: "waterlogging", notes: `Status: Named among locations that received BMC disaster-team waterlogging complaints | Source: Hindustan Times via PressReader` },
  { areaName: `Antop Hill`, lat: 19.0283439, lng: 72.869804, severity: "difficult", type: "waterlogging", notes: `Status: Named among locations that received BMC disaster-team waterlogging complaints | Source: Hindustan Times via PressReader` },
  { areaName: `SIES College area, Mulund`, lat: 19.0412952, lng: 72.8611248, severity: "difficult", type: "waterlogging", notes: `Status: Named among locations that received BMC disaster-team waterlogging complaints | Source: Hindustan Times via PressReader` },
  { areaName: `Mankhurd Railway Station area`, lat: 19.0484714, lng: 72.9323962, severity: "difficult", type: "waterlogging", notes: `Status: Named among locations that received BMC disaster-team waterlogging complaints | Source: Hindustan Times via PressReader` },
  { areaName: `Outer Ring Road (Sarjapur–Marathahalli stretch)`, lat: 12.9329898, lng: 77.6883564, severity: "impassable", type: "waterlogging", notes: `Status: Primary high-risk zone, tech corridor | Source: IMD yellow alert reporting, August 2026` },
  { areaName: `Sarjapur Road`, lat: 12.910911, lng: 77.6844166, severity: "impassable", type: "waterlogging", notes: `Status: Primary high-risk zone, tech corridor | Source: IMD yellow alert reporting, August 2026` },
  { areaName: `Bellandur (near Bellandur Lake)`, lat: 12.9357073, lng: 77.6716586, severity: "impassable", type: "waterlogging", notes: `Status: High-risk zone; lake near capacity during heavy rain | Source: news reporting, August 2026` },
  { areaName: `Whitefield`, lat: 12.9698196, lng: 77.7499721, severity: "difficult", type: "waterlogging", notes: `Status: High-risk tech corridor zone | Source: news reporting, August 2026` },
  { areaName: `Hebbal (Hebbal Valley)`, lat: 13.0353557, lng: 77.5987874, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone; floods when rainfall exceeds ~80mm | Source: BBMP officials, news reporting` },
  { areaName: `HSR Layout`, lat: 12.9121181, lng: 77.6445548, severity: "minor", type: "waterlogging", notes: `Status: Bulk of rain-related complaints from this low-lying layout | Source: Deccan Herald reporting` },
  { areaName: `Bellandur Kodi Main Road`, lat: 12.9275457, lng: 77.6814711, severity: "minor", type: "waterlogging", notes: `Status: Flood-hit stretch in IT corridor | Source: Deccan Herald reporting` },
  { areaName: `Yemalur`, lat: 12.9446164, lng: 77.6836756, severity: "minor", type: "waterlogging", notes: `Status: Flood-hit stretch in IT corridor | Source: Deccan Herald reporting` },
  { areaName: `Sony Signal, Koramangala`, lat: 12.9370476, lng: 77.6264252, severity: "clear", type: "waterlogging", notes: `Status: Vulnerable SWD point, 500m buffer radius — NOTE: from a 2020 BBMP list of 211 vulnerable stormwater drains; current status not confirmed | Source: Citizen Matters, June 2020` },
  { areaName: `Hennur Main Road`, lat: 13.0208861, lng: 77.6299432, severity: "clear", type: "waterlogging", notes: `Status: Chronic flood-prone area, official ministerial inspection site | Source: Udayavani reporting` },
  { areaName: `Manyata Tech Park area`, lat: 13.0474758, lng: 77.6199596, severity: "clear", type: "waterlogging", notes: `Status: Vulnerable SWD point, 650m buffer radius — NOTE: from a 2020 BBMP list of 211 vulnerable stormwater drains; current status not confirmed | Source: Citizen Matters, June 2020` },
  { areaName: `Koramangala`, lat: 12.9352403, lng: 77.624532, severity: "minor", type: "waterlogging", notes: `Status: Waterlogging reported after heavy rain spells | Source: Deccan Herald reporting` },
  { areaName: `Indiranagar`, lat: 12.9783692, lng: 77.6408356, severity: "minor", type: "waterlogging", notes: `Status: Waterlogging reported after heavy rain spells | Source: Deccan Herald reporting` },
  { areaName: `Seshadripuram`, lat: 12.9889055, lng: 77.574044, severity: "minor", type: "waterlogging", notes: `Status: Waterlogging reported after heavy rain spells | Source: Deccan Herald reporting` },
  { areaName: `K R Puram`, lat: 13.0169992, lng: 77.7044335, severity: "minor", type: "waterlogging", notes: `Status: Waterlogging reported after heavy rain spells | Source: Deccan Herald reporting` },
  { areaName: `LB Nagar`, lat: 17.3457176, lng: 78.5522296, severity: "impassable", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Uppal`, lat: 17.4015441, lng: 78.5681716, severity: "impassable", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Malkajgiri`, lat: 17.4503375, lng: 78.5322481, severity: "impassable", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Panjagutta`, lat: 17.4254486, lng: 78.450544, severity: "difficult", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Banjara Hills`, lat: 17.416889, lng: 78.43867, severity: "difficult", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Jubilee Hills`, lat: 17.4325894, lng: 78.4070691, severity: "difficult", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Begumpet`, lat: 17.4442397, lng: 78.4707916, severity: "minor", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Madhapur`, lat: 17.4485835, lng: 78.3908035, severity: "minor", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Gachibowli`, lat: 17.4400802, lng: 78.3489168, severity: "minor", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Miyapur`, lat: 17.5169014, lng: 78.3428304, severity: "clear", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Tolichowki`, lat: 17.3990023, lng: 78.4156933, severity: "clear", type: "waterlogging", notes: `Status: Named on a GHMC list of 123 waterlogging points — NOTE: this list dates to June 2019; I could not confirm it is still current | Source: The News Minute, June 2019` },
  { areaName: `Yamuna Bazar`, lat: 28.66482, lng: 77.23553, severity: "impassable", type: "waterlogging", notes: `Status: PWD-reported severe waterlogging point — NOTE: confirmed via a PWD list, but the underlying article is from Aug 2021, not necessarily current | Source: PWD list via The Tribune / Business Standard, Aug 2021` },
  { areaName: `Khanpur`, lat: 28.5077037, lng: 77.2321999, severity: "impassable", type: "waterlogging", notes: `Status: PWD-reported severe waterlogging point — NOTE: confirmed via a PWD list, but the underlying article is from Aug 2021, not necessarily current | Source: PWD list via The Tribune / Business Standard, Aug 2021` },
  { areaName: `Rohtak Road`, lat: 28.6820465, lng: 77.0706999, severity: "difficult", type: "waterlogging", notes: `Status: PWD-reported severe waterlogging point — NOTE: confirmed via a PWD list, but the underlying article is from Aug 2021, not necessarily current | Source: PWD list via The Tribune / Business Standard, Aug 2021` },
  { areaName: `Lodhi Road`, lat: 28.591085, lng: 77.2279773, severity: "difficult", type: "waterlogging", notes: `Status: PWD-reported severe waterlogging point — NOTE: confirmed via a PWD list, but the underlying article is from Aug 2021, not necessarily current | Source: PWD list via The Tribune / Business Standard, Aug 2021` },
  { areaName: `Azadpur Underpass`, lat: 28.7102323, lng: 77.1762172, severity: "minor", type: "waterlogging", notes: `Status: Chronic underpass waterlogging/closure spot — NOTE: confirmed via a PWD list, but the underlying article is from Aug 2021, not necessarily current | Source: PWD list via The Tribune / Business Standard, Aug 2021` },
  { areaName: `Zakhira Underpass`, lat: 28.667818, lng: 77.16415, severity: "minor", type: "waterlogging", notes: `Status: Chronic underpass waterlogging/closure spot — NOTE: confirmed via a PWD list, but the underlying article is from Aug 2021, not necessarily current | Source: PWD list via The Tribune / Business Standard, Aug 2021` },
  { areaName: `Patparganj Road Underpass (near Mother Dairy)`, lat: 28.6198887, lng: 77.2874308, severity: "clear", type: "waterlogging", notes: `Status: Chronic underpass waterlogging/closure spot — NOTE: confirmed via a PWD list, but the underlying article is from Aug 2021, not necessarily current | Source: PWD list via The Tribune / Business Standard, Aug 2021` },
  { areaName: `Kashmiri Gate`, lat: 28.6662201, lng: 77.229542, severity: "clear", type: "waterlogging", notes: `Status: Waterlogging complaints reported near metro station — NOTE: confirmed via a PWD list, but the underlying article is from Aug 2021, not necessarily current | Source: PWD list via The Tribune / Business Standard, Aug 2021` },
  { areaName: `Minto Bridge`, lat: 28.636414, lng: 77.222379, severity: "impassable", type: "waterlogging", notes: `Status: Perennial waterlogging hotspot, marked for special monitoring | Source: The Tribune reporting, 2026` },
  { areaName: `Pul Prahladpur Underpass`, lat: 28.4991114, lng: 77.2984488, severity: "impassable", type: "waterlogging", notes: `Status: Perennial waterlogging hotspot, marked for special monitoring | Source: The Tribune reporting, 2026` },
  { areaName: `Ring Road, opp. WHO building`, lat: 28.6221377, lng: 77.2475053, severity: "impassable", type: "waterlogging", notes: `Status: Perennial waterlogging hotspot, marked for special monitoring | Source: The Tribune reporting, 2026` },
  { areaName: `Jahangirpuri Metro Station Road`, lat: 28.7296171, lng: 77.1666313, severity: "impassable", type: "waterlogging", notes: `Status: Perennial waterlogging hotspot, marked for special monitoring | Source: The Tribune reporting, 2026` },
  { areaName: `Loni Road Golchakkar`, lat: 28.700864, lng: 77.2915529, severity: "impassable", type: "waterlogging", notes: `Status: Perennial waterlogging hotspot, marked for special monitoring | Source: The Tribune reporting, 2026` },
  { areaName: `Karala–Kanjhawla stretch`, lat: 28.7406198, lng: 77.0362967, severity: "impassable", type: "waterlogging", notes: `Status: Perennial waterlogging hotspot, marked for special monitoring | Source: The Tribune reporting, 2026` },
  { areaName: `Industrial Area, Phase I`, lat: 30.7003182, lng: 76.8033116, severity: "impassable", type: "waterlogging", notes: `Status: Low-lying area; confirmed as a recurring waterlogging spot across multiple years of Tribune reporting, most recently Aug 2026 | Source: The Tribune, multiple years incl. Aug 2026` },
  { areaName: `Ram Darbar`, lat: 30.691482, lng: 76.7927981, severity: "impassable", type: "waterlogging", notes: `Status: Low-lying area; confirmed as a recurring waterlogging spot across multiple years of Tribune reporting, most recently Aug 2026 | Source: The Tribune, multiple years incl. Aug 2026` },
  { areaName: `Manimajra`, lat: 30.7156603, lng: 76.834619, severity: "difficult", type: "waterlogging", notes: `Status: Low-lying area; confirmed as a recurring waterlogging spot across multiple years of Tribune reporting, most recently Aug 2026 | Source: The Tribune, multiple years incl. Aug 2026` },
  { areaName: `Hallomajra`, lat: 30.6867029, lng: 76.7951389, severity: "difficult", type: "waterlogging", notes: `Status: Low-lying area; confirmed as a recurring waterlogging spot across multiple years of Tribune reporting, most recently Aug 2026 | Source: The Tribune, multiple years incl. Aug 2026` },
  { areaName: `Sector 22/23 Roundabout`, lat: 30.730261, lng: 76.774331, severity: "minor", type: "waterlogging", notes: `Status: A tree fell on a bus here during heavy rain (Sept 2025); the specific "CBD slab repair" claim previously here could not be verified and has been removed | Source: Tribune ePaper, Sept 2025` },
  { areaName: `DD Nagar, Zone-5`, lat: 21.238872, lng: 81.61854, severity: "impassable", type: "waterlogging", notes: `Status: Knee-deep water entered homes, July 2026 monsoon spell | Source: The Hitavada reporting, July 2026` },
  { areaName: `Shankar Nagar`, lat: 21.2510977, lng: 81.6675975, severity: "difficult", type: "waterlogging", notes: `Status: Houses flooded, July 2026 monsoon spell | Source: The Hitavada reporting, July 2026` },
  { areaName: `Tatibandh`, lat: 21.2614068, lng: 81.5759054, severity: "difficult", type: "waterlogging", notes: `Status: Houses flooded, July 2026 monsoon spell | Source: The Hitavada reporting, July 2026` },
  { areaName: `Indraprastha Colony, Phase-2 (EWS B-Block)`, lat: 21.2364417, lng: 81.5868209, severity: "minor", type: "waterlogging", notes: `Status: Houses flooded, July 2026 monsoon spell | Source: The Hitavada reporting, July 2026` },
  { areaName: `Velachery (incl. Velachery Main Road)`, lat: 12.9754605, lng: 80.2207047, severity: "impassable", type: "waterlogging", notes: `Status: City's most flood-vulnerable mid-segment area; history of 2015 flooding | Source: news reporting, 2026` },
  { areaName: `Madipakkam`, lat: 12.9647462, lng: 80.1960832, severity: "impassable", type: "waterlogging", notes: `Status: On flood-watch list, marsh-adjacent stretch | Source: news reporting, 2026` },
  { areaName: `Adambakkam`, lat: 12.9880288, lng: 80.2047133, severity: "impassable", type: "waterlogging", notes: `Status: On flood-watch list | Source: news reporting, 2026` },
  { areaName: `Pallikaranai (marsh region)`, lat: 12.9348912, lng: 80.2137124, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone; built on aquifer-bearing marshland with obstructed natural drainage | Source: flood-risk mapping, 2026` },
  { areaName: `Tambaram West`, lat: 12.9371762, lng: 80.1112313, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone along the Adyar river | Source: flood-risk mapping, 2026` },
  { areaName: `Ambattur (SIDCO)`, lat: 13.1030737, lng: 80.1718166, severity: "minor", type: "waterlogging", notes: `Status: Specifically flagged ahead of 2026 Northeast Monsoon; missing stormwater-drain connections near construction sites | Source: news reporting, Sept 2026` },
  { areaName: `Manali`, lat: 13.1779289, lng: 80.2700737, severity: "minor", type: "waterlogging", notes: `Status: Specifically flagged ahead of 2026 Northeast Monsoon | Source: news reporting, Sept 2026` },
  { areaName: `T. Nagar`, lat: 13.0417591, lng: 80.2340761, severity: "clear", type: "waterlogging", notes: `Status: Priority ward for GCC's 2026-27 stormwater drainage expansion (Rs 1,341 cr climate budget) | Source: news reporting, 2026` },
  { areaName: `Mylapore`, lat: 13.0367914, lng: 80.2676303, severity: "clear", type: "waterlogging", notes: `Status: Priority ward for drainage expansion; 1970s storm-water layouts overwhelmed | Source: news reporting, 2026` },
  { areaName: `Adyar`, lat: 13.0011774, lng: 80.2564957, severity: "clear", type: "waterlogging", notes: `Status: Priority ward for GCC's 2026-27 stormwater drainage expansion | Source: news reporting, 2026` },
  { areaName: `Perungudi`, lat: 12.9653652, lng: 80.2461057, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone, east of OMR | Source: flood-risk mapping, 2026` },
  { areaName: `Sholinganallur`, lat: 12.9009877, lng: 80.2279301, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone, sits on filled-marsh land | Source: flood-risk mapping, 2026` },
  { areaName: `West Mambalam`, lat: 13.0382876, lng: 80.2209499, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone, 1970s storm-water layouts overwhelmed | Source: flood-risk mapping, 2026` },
  { areaName: `Bansdroni`, lat: 22.4707774, lng: 88.3617951, severity: "impassable", type: "waterlogging", notes: `Status: Waterlogged for ~3 days after the Sept 2025 cloudburst, one of the hardest-hit southern pockets | Source: Wikipedia, "September 2025 Kolkata cloudburst"` },
  { areaName: `Jadavpur`, lat: 22.4954988, lng: 88.3709008, severity: "impassable", type: "waterlogging", notes: `Status: Waterlogged for ~3 days after Sept 2025 cloudburst | Source: Sept 2025 Kolkata cloudburst reporting` },
  { areaName: `Garia (Kamdahari)`, lat: 22.4637707, lng: 88.3777956, severity: "impassable", type: "waterlogging", notes: `Status: Recorded 332mm of rain within a few hours during the Sept 2025 cloudburst — among the highest single-spell totals recorded in the city that year; waterlogged for roughly 3 days afterward | Source: Wikipedia, "September 2025 Kolkata cloudburst"` },
  { areaName: `Behala`, lat: 22.5015719, lng: 88.3209437, severity: "difficult", type: "waterlogging", notes: `Status: Chronic waterlogging; some pockets stay partially inundated for months of the year | Source: KMC drainage reporting, 2026` },
  { areaName: `Tollygunge`, lat: 22.4986357, lng: 88.3453906, severity: "difficult", type: "waterlogging", notes: `Status: Chronic waterlogging, medium-to-heavy showers take a long time to clear | Source: KMC drainage reporting, 2026` },
  { areaName: `Garden Reach`, lat: 22.5485456, lng: 88.2876393, severity: "difficult", type: "waterlogging", notes: `Status: Chronic waterlogging, medium-to-heavy showers take a long time to clear | Source: KMC drainage reporting, 2026` },
  { areaName: `Thanthania`, lat: 22.5810907, lng: 88.3656242, severity: "minor", type: "waterlogging", notes: `Status: Repeatedly among worst-hit stretches in heavy downpours | Source: Times of India reporting, 2026` },
  { areaName: `Sealdah`, lat: 22.567792, lng: 88.3710203, severity: "minor", type: "waterlogging", notes: `Status: Repeatedly among worst-hit stretches in heavy downpours | Source: Times of India reporting, 2026` },
  { areaName: `Ultadanga`, lat: 22.5944516, lng: 88.3835325, severity: "minor", type: "waterlogging", notes: `Status: Repeatedly among worst-hit stretches in heavy downpours | Source: Times of India reporting, 2026` },
  { areaName: `Salt Lake / Sector V`, lat: 22.580939, lng: 88.429052, severity: "clear", type: "waterlogging", notes: `Status: Large parts inundated in heavy-rain events; IT corridor | Source: Times of India reporting, 2026` },
  { areaName: `Camac Street`, lat: 22.5462899, lng: 88.3529355, severity: "minor", type: "waterlogging", notes: `Status: Repeatedly among worst-hit stretches in heavy downpours | Source: Times of India reporting, 2026` },
  { areaName: `Amherst Street`, lat: 22.5786481, lng: 88.36963, severity: "minor", type: "waterlogging", notes: `Status: Repeatedly among worst-hit stretches in heavy downpours | Source: Times of India reporting, 2026` },
  { areaName: `Kankurgachi`, lat: 22.5802167, lng: 88.3905869, severity: "minor", type: "waterlogging", notes: `Status: Repeatedly among worst-hit stretches in heavy downpours | Source: Times of India reporting, 2026` },
  { areaName: `Alipore`, lat: 22.5251784, lng: 88.3308634, severity: "minor", type: "waterlogging", notes: `Status: Recorded 251mm rain in the Sept 2025 cloudburst | Source: Sept 2025 Kolkata cloudburst reporting` },
  { areaName: `Fatimanagar`, lat: 18.5042104, lng: 73.9014439, severity: "impassable", type: "waterlogging", notes: `Status: Flagged A/A+ grade hotspot by Pune Traffic Police | Source: Pune Traffic Police list, July 2026` },
  { areaName: `Radha Hotel Chowk, Baner`, lat: 18.569904, lng: 73.765857, severity: "impassable", type: "waterlogging", notes: `Status: Flagged waterlogging hotspot by Pune Traffic Police | Source: Pune Traffic Police list, July 2026` },
  { areaName: `North Main Road, Mundhwa`, lat: 18.5358903, lng: 73.9108087, severity: "difficult", type: "waterlogging", notes: `Status: Flagged waterlogging hotspot by Pune Traffic Police | Source: Pune Traffic Police list, July 2026` },
  { areaName: `Stretch beneath Ruby Hall Metro Station`, lat: 18.532694, lng: 73.877848, severity: "difficult", type: "waterlogging", notes: `Status: Flagged waterlogging hotspot by Pune Traffic Police | Source: Pune Traffic Police list, July 2026` },
  { areaName: `Rajaram Bridge`, lat: 18.4884771, lng: 73.8278975, severity: "minor", type: "waterlogging", notes: `Status: Flagged waterlogging hotspot by Pune Traffic Police | Source: Pune Traffic Police list, July 2026` },
  { areaName: `Gunjan Talkies area`, lat: 18.5465148, lng: 73.8887566, severity: "minor", type: "waterlogging", notes: `Status: Flagged waterlogging hotspot by Pune Traffic Police | Source: Pune Traffic Police list, July 2026` },
  { areaName: `Bhairobanala Chowk`, lat: 18.506878, lng: 73.897841, severity: "difficult", type: "waterlogging", notes: `Status: Flagged waterlogging hotspot by Pune Traffic Police | Source: Pune Traffic Police list, July 2026` },
  { areaName: `Seven Loves Chowk`, lat: 18.5016653, lng: 73.8689267, severity: "difficult", type: "waterlogging", notes: `Status: Flagged waterlogging hotspot by Pune Traffic Police | Source: Pune Traffic Police list, July 2026` },
  { areaName: `Nikol`, lat: 23.0499889, lng: 72.6699673, severity: "impassable", type: "waterlogging", notes: `Status: Knee-deep waterlogging in July 2026 deluge | Source: Gujarat Samachar reporting, July 2026` },
  { areaName: `Vastral`, lat: 22.9978372, lng: 72.665991, severity: "impassable", type: "waterlogging", notes: `Status: Chronic waterlogging; poor drainage, near Sabarmati overflow channels | Source: flood-risk mapping, 2026` },
  { areaName: `Maninagar`, lat: 22.995165, lng: 72.604097, severity: "impassable", type: "waterlogging", notes: `Status: Knee-deep waterlogging in July 2026 deluge | Source: Gujarat Samachar reporting, July 2026` },
  { areaName: `Naroda`, lat: 23.0685865, lng: 72.6535961, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone, poor drainage | Source: AMC/GSDMA flood hazard maps` },
  { areaName: `Vatva`, lat: 22.9664255, lng: 72.6159326, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone, poor drainage | Source: AMC/GSDMA flood hazard maps` },
  { areaName: `Shahibaug`, lat: 23.0560932, lng: 72.5961666, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone, low-lying near Sabarmati | Source: AMC/GSDMA flood hazard maps` },
  { areaName: `Jamalpur`, lat: 23.0128963, lng: 72.5848081, severity: "difficult", type: "waterlogging", notes: `Status: High-risk zone, low-lying near Sabarmati | Source: AMC/GSDMA flood hazard maps` },
  { areaName: `Bopal`, lat: 23.0336769, lng: 72.4634117, severity: "minor", type: "waterlogging", notes: `Status: Moderate-risk zone; once safe, rapid construction blocked natural drainage | Source: flood-risk mapping, 2026` },
  { areaName: `Sarkhej`, lat: 22.9778146, lng: 72.4979419, severity: "impassable", type: "waterlogging", notes: `Status: Worst-hit western corridor, 14.13 inches rain in July 2026 deluge | Source: Gujarat Samachar reporting, July 2026` },
  { areaName: `Gota`, lat: 23.1012966, lng: 72.5407052, severity: "minor", type: "waterlogging", notes: `Status: Waterlogged over 48 hours in 2021, watch-listed since | Source: Terranexxus flood-zone guide, 2026` },
  { areaName: `Chandkheda`, lat: 23.109098, lng: 72.5849179, severity: "minor", type: "waterlogging", notes: `Status: Waterlogged over 48 hours in 2021, watch-listed since | Source: Terranexxus flood-zone guide, 2026` },
  { areaName: `Mithakhali underpass`, lat: 23.0293787, lng: 72.5689942, severity: "impassable", type: "waterlogging", notes: `Status: Underpass shut down to vehicular traffic after filling with water during a 4-inch, 3-hour downpour | Source: Deccan Herald reporting` },
  { areaName: `Vejalpur`, lat: 23.0061051, lng: 72.5164075, severity: "impassable", type: "waterlogging", notes: `Status: Received about 140mm of rainfall in under 3 hours, among the worst-affected western areas | Source: Deccan Herald reporting` },
  { areaName: `Bodakdev`, lat: 23.0386593, lng: 72.5118581, severity: "difficult", type: "waterlogging", notes: `Status: Received about 109mm of rainfall in under 3 hours | Source: Deccan Herald reporting` },
  { areaName: `Simada Creek area`, lat: 21.2219001, lng: 72.9000647, severity: "impassable", type: "waterlogging", notes: `Status: Creek water levels breached danger mark, July 2026 | Source: Gujarat Samachar reporting, July 2026` },
  { areaName: `Bhedwad Creek area`, lat: 21.1522168, lng: 72.8394321, severity: "impassable", type: "waterlogging", notes: `Status: Creek water levels breached danger mark, July 2026 | Source: Gujarat Samachar reporting, July 2026` },
  { areaName: `Katargam (low-lying zone)`, lat: 21.2266205, lng: 72.8312383, severity: "difficult", type: "waterlogging", notes: `Status: Among ~34 low-lying communities flooded, 2200+ evacuated citywide | Source: Gujarat Samachar reporting, July 2026` },
  { areaName: `Central Surat (Tapi causeway area)`, lat: 21.2261984, lng: 72.8042769, severity: "difficult", type: "waterlogging", notes: `Status: Tapi causeway closed to motorists during heavy rain events | Source: news reporting` },
  { areaName: `Udhna`, lat: 21.1431152, lng: 72.8431097, severity: "difficult", type: "waterlogging", notes: `Status: Waterlogging reported putting vehicular traffic in trouble after heavy rain | Source: Deccan Herald reporting` },
  { areaName: `Varachha`, lat: 21.2021189, lng: 72.8672703, severity: "difficult", type: "waterlogging", notes: `Status: Waterlogging reported putting vehicular traffic in trouble after heavy rain | Source: Deccan Herald reporting` },
  { areaName: `Pandesara`, lat: 21.1502576, lng: 72.8249607, severity: "difficult", type: "waterlogging", notes: `Status: Waterlogging reported putting vehicular traffic in trouble after heavy rain | Source: Deccan Herald reporting` },
  { areaName: `Dak Bungalow Road`, lat: 25.6100991, lng: 85.1365224, severity: "impassable", type: "waterlogging", notes: `Status: Knee-deep water, road and rail connectivity crippled — NOTE: corrected date, this was July 2025, not 2026 | Source: NewKerala/Gulf News/IANS wire report, July 28, 2025` },
  { areaName: `Patna Junction`, lat: 25.6030111, lng: 85.1372459, severity: "impassable", type: "waterlogging", notes: `Status: Knee-deep water, rail connectivity crippled — NOTE: corrected date, this was July 2025, not 2026 | Source: NewKerala/Gulf News/IANS wire report, July 28, 2025` },
  { areaName: `Boring Road`, lat: 25.6173095, lng: 85.1155029, severity: "impassable", type: "waterlogging", notes: `Status: Knee-deep water flooded this high-profile area — NOTE: corrected date, this was July 2025, not 2026 | Source: NewKerala/Gulf News/IANS wire report, July 28, 2025` },
  { areaName: `Rajendra Nagar`, lat: 25.6068056, lng: 85.1651556, severity: "impassable", type: "waterlogging", notes: `Status: Knee-deep water flooded this high-profile area — NOTE: corrected date, this was July 2025, not 2026 | Source: NewKerala/Gulf News/IANS wire report, July 28, 2025` },
  { areaName: `Station Road`, lat: 25.6055605, lng: 85.1392169, severity: "impassable", type: "waterlogging", notes: `Status: Knee-deep water flooded this high-profile area — NOTE: corrected date, this was July 2025, not 2026 | Source: NewKerala/Gulf News/IANS wire report, July 28, 2025` },
  { areaName: `Six Mile`, lat: 26.1313516, lng: 91.8044127, severity: "impassable", type: "waterlogging", notes: `Status: Water rose knee-deep; busy arterial corridor, 2026 | Source: Sentinel Assam reporting, 2026` },
  { areaName: `Khanapara`, lat: 26.121255, lng: 91.8208179, severity: "impassable", type: "waterlogging", notes: `Status: Water rose knee-deep along the Six Mile–Khanapara corridor | Source: Sentinel Assam reporting, 2026` },
  { areaName: `VIP Road`, lat: 26.1590621, lng: 91.8176699, severity: "impassable", type: "waterlogging", notes: `Status: Large stretches went underwater, vehicles broke down mid-journey | Source: Sentinel Assam reporting, 2026` },
  { areaName: `Beltola`, lat: 26.1286243, lng: 91.8012675, severity: "difficult", type: "waterlogging", notes: `Status: Water rose knee-deep, 2026 | Source: Sentinel Assam reporting, 2026` },
  { areaName: `Hatigaon`, lat: 26.1290668, lng: 91.7794133, severity: "difficult", type: "waterlogging", notes: `Status: Significant waterlogging reported, Sept 2026 | Source: Guwahatipedia reporting, Sept 2026` },
  { areaName: `Maligaon`, lat: 26.1503648, lng: 91.6959821, severity: "difficult", type: "waterlogging", notes: `Status: Among worst-affected low-lying areas | Source: Assam Times reporting, July 2026` },
  { areaName: `Silpukhuri`, lat: 26.1888243, lng: 91.7651427, severity: "minor", type: "waterlogging", notes: `Status: Among worst-affected low-lying areas | Source: Assam Times reporting, July 2026` },
  { areaName: `Chandmari`, lat: 26.1895075, lng: 91.7723695, severity: "minor", type: "waterlogging", notes: `Status: Among worst-affected low-lying areas | Source: Assam Times reporting, July 2026` },
  { areaName: `Geeta Mandir`, lat: 26.1745677, lng: 91.8006903, severity: "difficult", type: "waterlogging", notes: `Status: Water rose knee-deep, 2026 | Source: Sentinel Assam reporting, 2026` },
  { areaName: `AIDC`, lat: 26.1697766, lng: 91.7792159, severity: "difficult", type: "waterlogging", notes: `Status: Water rose knee-deep, 2026 | Source: Sentinel Assam reporting, 2026` },
  { areaName: `Rukminigaon`, lat: 26.1361511, lng: 91.7968335, severity: "minor", type: "waterlogging", notes: `Status: Significant waterlogging reported, Sept 2026 | Source: Guwahatipedia reporting, Sept 2026` },
  { areaName: `Panjabari`, lat: 26.1313284, lng: 91.8210154, severity: "minor", type: "waterlogging", notes: `Status: Significant waterlogging reported, Sept 2026 | Source: Guwahatipedia reporting, Sept 2026` },
  { areaName: `Wireless (Basistha)`, lat: 26.1344712, lng: 91.7910132, severity: "impassable", type: "waterlogging", notes: `Status: Reported significant waterlogging in the first days of Sept 2026, among the most recent confirmed spots | Source: Guwahatipedia, published Sept 5, 2026` },
  { areaName: `Narengi`, lat: 26.1785676, lng: 91.829256, severity: "impassable", type: "waterlogging", notes: `Status: Part of the Narengi–Six Mile–Panjabari corridor named as among the worst-affected in the Sept 2026 spell | Source: Guwahatipedia, published Sept 5, 2026` },
  { areaName: `Indira Nagar`, lat: 26.8798933, lng: 80.9926327, severity: "difficult", type: "waterlogging", notes: `Status: Heavy waterlogging reported during 2021 downpour | Source: Hindustan Times via PressReader` },
  { areaName: `Faizullaganj`, lat: 26.8960904, lng: 80.9227965, severity: "difficult", type: "waterlogging", notes: `Status: Heavy waterlogging reported | Source: Hindustan Times via PressReader` },
  { areaName: `Mahanagar`, lat: 26.8733642, lng: 80.9574467, severity: "difficult", type: "waterlogging", notes: `Status: Waterlogging and power breakdowns after rainwater entered sub-stations | Source: Hindustan Times via PressReader` },
  { areaName: `Aliganj`, lat: 26.8983705, lng: 80.9491069, severity: "minor", type: "waterlogging", notes: `Status: Heavy waterlogging reported | Source: Hindustan Times via PressReader` },
  { areaName: `Alambagh`, lat: 26.8127442, lng: 80.9012798, severity: "minor", type: "waterlogging", notes: `Status: Heavy waterlogging reported | Source: Hindustan Times via PressReader` },
  { areaName: `Hazratganj`, lat: 26.8541536, lng: 80.9447827, severity: "minor", type: "waterlogging", notes: `Status: Heavy waterlogging reported | Source: Hindustan Times via PressReader` },
  { areaName: `Charbagh`, lat: 26.8322933, lng: 80.9214337, severity: "minor", type: "waterlogging", notes: `Status: Heavy waterlogging reported | Source: Hindustan Times via PressReader` },
  { areaName: `Gomti Nagar (Inox area)`, lat: 26.8530243, lng: 80.9733788, severity: "difficult", type: "waterlogging", notes: `Status: Pedestrians wading through knee-deep water | Source: Hindustan Times via PressReader` },
  { areaName: `Eldeco Udyan-2 (lakeside road)`, lat: 26.7653, lng: 80.9436, severity: "impassable", type: "waterlogging", notes: `Status: Potholes reported on lakeside road, water hid pothole depth, 2026 — NOTE: coordinate corrected in second geocoding pass to the actual Eldeco Udyan-2 lake, ~5km from the previous (incorrect) estimate | Source: local news reporting, 2026` },
  { areaName: `Sikar Road`, lat: 26.9801573, lng: 75.7744654, severity: "difficult", type: "waterlogging", notes: `Status: Submerged after heavy rainfall | Source: Deccan Herald reporting, 2024` },
  { areaName: `Jal Mahal area`, lat: 26.9534584, lng: 75.8461235, severity: "difficult", type: "waterlogging", notes: `Status: Submerged after heavy rainfall | Source: Deccan Herald reporting, 2024` },
  { areaName: `Tonk Road`, lat: 26.8313319, lng: 75.794154, severity: "minor", type: "waterlogging", notes: `Status: Rainwater accumulation, traffic disruption | Source: Deccan Herald reporting, 2024` },
  { areaName: `SMS Hospital premises`, lat: 26.906234, lng: 75.8163148, severity: "minor", type: "waterlogging", notes: `Status: Rainwater accumulation | Source: Deccan Herald reporting, 2024` },
  { areaName: `B2 Bypass`, lat: 26.8528837, lng: 75.7617543, severity: "minor", type: "waterlogging", notes: `Status: Rainwater accumulation | Source: Deccan Herald reporting, 2024` },
  { areaName: `Jawahar Nagar`, lat: 26.8892814, lng: 75.8360422, severity: "minor", type: "waterlogging", notes: `Status: Rainwater accumulation | Source: Deccan Herald reporting, 2024` },
  { areaName: `Vidyadhar Nagar`, lat: 26.9621084, lng: 75.7816265, severity: "minor", type: "waterlogging", notes: `Status: Rainwater accumulation | Source: Deccan Herald reporting, 2024` },
  { areaName: `Ernakulam South Railway Station area`, lat: 9.968525, lng: 76.2893149, severity: "impassable", type: "waterlogging", notes: `Status: South railway station and bus stand flooded owing to waterlogging | Source: Deccan Herald reporting` },
  { areaName: `Kaloor`, lat: 9.9921355, lng: 76.3019038, severity: "difficult", type: "waterlogging", notes: `Status: Stormwater entered many houses | Source: Deccan Herald reporting` },
  { areaName: `Edappally`, lat: 10.0260688, lng: 76.3124753, severity: "difficult", type: "waterlogging", notes: `Status: Stormwater entered many houses | Source: Deccan Herald reporting` },
  { areaName: `Kalamassery`, lat: 10.0531493, lng: 76.3528075, severity: "difficult", type: "waterlogging", notes: `Status: Stormwater entered many houses, relief camps opened | Source: Deccan Herald reporting` },
  { areaName: `Karond`, lat: 23.2950654, lng: 77.4037183, severity: "impassable", type: "waterlogging", notes: `Status: Water accumulated for nearly two days, Aug 2026 | Source: Free Press Journal reporting, Aug 2026` },
  { areaName: `Khejda`, lat: 23.2941, lng: 77.4157, severity: "impassable", type: "waterlogging", notes: `Status: Water accumulated for nearly two days, Aug 2026 — NOTE: coordinate updated in second geocoding pass to sit adjacent to Bhanpur/Karond, matching the article's grouping of these three localities; still not a direct place-name match, so treat as approximate | Source: Free Press Journal reporting, Aug 2026` },
  { areaName: `Chhola`, lat: 23.2758535, lng: 77.4149023, severity: "impassable", type: "waterlogging", notes: `Status: Water accumulated for nearly two days, Aug 2026 | Source: Free Press Journal reporting, Aug 2026` },
  { areaName: `Alpana Tiraha`, lat: 23.2646643, lng: 77.4098127, severity: "difficult", type: "waterlogging", notes: `Status: Longstanding unresolved waterlogging hotspot | Source: Free Press Journal reporting, July 2026` },
  { areaName: `Manish Nagar`, lat: 21.0938434, lng: 79.0750138, severity: "impassable", type: "waterlogging", notes: `Status: Chronic hotspot; a single 70.6mm rain spell in July 2026 left knee-level water disrupting transit routes | Note: Bombay High Court's Nagpur bench took suo motu cognisance of recurring flooding here despite NMC's annual desilting claims | Source: The Hitavada / The Live Nagpur, July 2026` },
  { areaName: `Mankapur`, lat: 21.184646, lng: 79.0787894, severity: "impassable", type: "waterlogging", notes: `Status: Chronic hotspot, knee-level water disrupts transit, July 2026 | Source: The Hitavada reporting, July 2026` },
  { areaName: `Loha Pul`, lat: 21.1451354, lng: 79.0884757, severity: "impassable", type: "waterlogging", notes: `Status: Chronic waterlogging under rail bridge, compounded by potholes and narrow roads causing constant traffic jams | Note: Municipal Commissioner Dr Vipin Itankar directed railway officials during a site inspection to deliver a permanent solution within a week | Source: The Hitavada reporting, July 2026` },
  { areaName: `Narendra Nagar`, lat: 21.1041408, lng: 79.0772749, severity: "difficult", type: "waterlogging", notes: `Status: Becomes virtually inaccessible in heavy rain; NMC deployed high-capacity pumps at the underpass | Source: The Live Nagpur / Bombay HC reporting, July 2026` },
  { areaName: `Ambazari Layout`, lat: 21.1327607, lng: 79.0485164, severity: "minor", type: "waterlogging", notes: `Status: Waterlogging reported during heavy downpour | Source: Deccan Herald reporting` },
  { areaName: `Shankar Nagar`, lat: 21.1336497, lng: 79.0617831, severity: "minor", type: "waterlogging", notes: `Status: Waterlogging reported during heavy downpour | Source: Deccan Herald reporting` },
  { areaName: `Trimurti Nagar`, lat: 21.118064, lng: 79.0450328, severity: "minor", type: "waterlogging", notes: `Status: Waterlogging reported during heavy downpour | Source: Deccan Herald reporting` },
  { areaName: `Wathoda`, lat: 21.1378715, lng: 79.1365083, severity: "minor", type: "waterlogging", notes: `Status: Waterlogging reported during heavy downpour | Source: Deccan Herald reporting` },
  { areaName: `Bombay Hospital area`, lat: 22.7543445, lng: 75.9033461, severity: "difficult", type: "waterlogging", notes: `Status: Commissioner inspected this waterlogging-prone spot, July 2026, as part of an 11-location tour after continuous rainfall exposed drainage gaps | Source: Free Press Journal reporting, July 2026` },
  { areaName: `Lasudia Mori`, lat: 22.7789113, lng: 75.903933, severity: "difficult", type: "waterlogging", notes: `Status: Commissioner inspected this waterlogging-prone spot, July 2026 | Source: Free Press Journal reporting, July 2026` },
  { areaName: `Panchwati Colony`, lat: 22.7925458, lng: 75.9049493, severity: "impassable", type: "waterlogging", notes: `Status: Private construction found to have physically damaged a stormwater drain here, causing severe waterlogging | Note: IMC Commissioner Kshitij Singhal ordered the construction work halted immediately and directed action against those responsible | Source: Free Press Journal reporting, July 2026` },
  { areaName: `LIG Square`, lat: 22.7372765, lng: 75.8908828, severity: "minor", type: "waterlogging", notes: `Status: Commissioner inspected this waterlogging-prone spot, July 2026 | Source: Free Press Journal reporting, July 2026` },
  { areaName: `Palasia Square`, lat: 22.7240867, lng: 75.8859818, severity: "minor", type: "waterlogging", notes: `Status: Commissioner inspected this waterlogging-prone spot, July 2026 | Source: Free Press Journal reporting, July 2026` },
  { areaName: `Khajrana Square`, lat: 22.7317086, lng: 75.9029529, severity: "minor", type: "waterlogging", notes: `Status: Commissioner inspected this waterlogging-prone spot, July 2026 | Source: Free Press Journal reporting, July 2026` },
  { areaName: `Robot Square`, lat: 22.7412187, lng: 75.9024797, severity: "minor", type: "waterlogging", notes: `Status: Commissioner inspected this waterlogging-prone spot, July 2026 | Source: Free Press Journal reporting, July 2026` },
  { areaName: `Vadsar`, lat: 22.2603943, lng: 73.1733127, severity: "impassable", type: "waterlogging", notes: `Status: NDRF rescued ~16 people stranded in flood water here as the Vishwamitri River overflowed 12 feet above its danger mark | Source: Deccan Herald / All India Radio reporting, 2024` },
  { areaName: `Kamtaipura`, lat: 22.3186734, lng: 73.1884305, severity: "difficult", type: "waterlogging", notes: `Status: Low-lying area flooded as Vishwamitri overflowed; community kitchens set up for stranded residents | Source: Deccan Herald reporting, 2024` },
  { areaName: `Sayajigunj`, lat: 22.3089762, lng: 73.1880353, severity: "difficult", type: "waterlogging", notes: `Status: Municipal school here took in displaced residents during major flood evacuation | Source: Deccan Herald reporting, 2024` },
  { areaName: `Pursorambhatta`, lat: 22.3024072, lng: 73.1814248, severity: "difficult", type: "waterlogging", notes: `Status: Residents evacuated to a Sayajigunj municipal school as Vishwamitri floodwaters entered homes; name corrected from an earlier mis-transcription | Source: Deccan Herald reporting, 2024` },
  { areaName: `Avinashi flyover (Central Zone)`, lat: 11.0020632, lng: 76.9649031, severity: "difficult", type: "waterlogging", notes: `Status: Two 100 HP motors fixed beneath the flyover to prevent inundation blocking traffic | Source: DT Next, May 2025` },
  { areaName: `Kaleeswara Mills area`, lat: 11.0051013, lng: 76.9632259, severity: "difficult", type: "waterlogging", notes: `Status: High-power motor fixed here to pump out water | Source: DT Next, May 2025` },
  { areaName: `Goodshed Road`, lat: 10.9976522, lng: 76.9652498, severity: "minor", type: "waterlogging", notes: `Status: Commissioner directed urgent desilting of stormwater drains here | Source: DT Next, May 2025` },
  { areaName: `Near Royal Theatre`, lat: 10.9929972, lng: 76.9666918, severity: "minor", type: "waterlogging", notes: `Status: Commissioner directed urgent desilting of stormwater drains here | Source: DT Next, May 2025` },
  { areaName: `Trichy Road (parts)`, lat: 10.9976605, lng: 77.0126952, severity: "minor", type: "waterlogging", notes: `Status: Commissioner directed urgent desilting of stormwater drains here | Source: DT Next, May 2025` },
  { areaName: `Kurichi Lake area`, lat: 10.9660117, lng: 76.9690125, severity: "clear", type: "waterlogging", notes: `Status: Fire safety rescue drills held here as part of monsoon emergency preparedness | Source: DT Next, May 2025` },
  { areaName: `Hanspal`, lat: 20.3150904, lng: 85.8824334, severity: "impassable", type: "waterlogging", notes: `Status: Severe waterlogging; rainwater entered homes, reaching waist level in some areas | Source: Odisha Connect reporting, Aug 2026` },
  { areaName: `Haridaspur`, lat: 20.3344897, lng: 85.8729305, severity: "impassable", type: "waterlogging", notes: `Status: Severe waterlogging; roads submerged under knee-deep water | Source: Odisha Connect reporting, Aug 2026` },
  { areaName: `Millennium City, Pahala`, lat: 20.3378979, lng: 85.8814166, severity: "difficult", type: "waterlogging", notes: `Status: Severe waterlogging disrupting daily commuting | Source: Odisha Connect reporting, Aug 2026` },
  { areaName: `GGP Colony (Tarini Basti / Jagannath Basti)`, lat: 20.2934448, lng: 85.8658955, severity: "impassable", type: "waterlogging", notes: `Status: Near-flood conditions in Laxmisagar police station limits | Source: Odisha Connect reporting, Aug 2026` },
  { areaName: `Bandhgari (Sadar PS area)`, lat: 23.3864415, lng: 85.3723547, severity: "impassable", type: "waterlogging", notes: `Status: ~40 people rescued by NDRF from this locality after heavy rain left the area flooded, under Sadar police station limits — NOTE: corrected date, this was August 2024, not 2026 | Source: PTI wire report via Business Standard/Tribune/Deccan Herald, Aug 3, 2024` },
  { areaName: `Mandar`, lat: 23.4586973, lng: 85.0921648, severity: "difficult", type: "waterlogging", notes: `Status: Road diversion washed away in heavy rain — NOTE: corrected date, this was August 2024, not 2026 | Source: PTI wire report via Business Standard/Tribune/Deccan Herald, Aug 3, 2024` },
  { areaName: `Madan Mohan Malviya Road`, lat: 31.6384056, lng: 74.875659, severity: "difficult", type: "waterlogging", notes: `Status: Rainwater accumulated for hours despite MC desilting claims | Source: The Tribune reporting` },
  { areaName: `Rani Ka Bagh (near Government College)`, lat: 31.638763, lng: 74.8580233, severity: "difficult", type: "waterlogging", notes: `Status: Regular waterlogging during monsoon season | Source: The Tribune reporting` },
  { areaName: `Majitha Road`, lat: 31.6555635, lng: 74.888147, severity: "minor", type: "waterlogging", notes: `Status: Regular waterlogging during monsoon season | Source: The Tribune reporting` },
  { areaName: `Circular Road`, lat: 31.6538639, lng: 74.8677173, severity: "minor", type: "waterlogging", notes: `Status: Regular waterlogging during monsoon season | Source: The Tribune reporting` },
  { areaName: `Chheharta`, lat: 31.6275194, lng: 74.792645, severity: "minor", type: "waterlogging", notes: `Status: Regular waterlogging during monsoon season | Source: The Tribune reporting` },
  { areaName: `Kot Khalsa`, lat: 31.6237318, lng: 74.8258562, severity: "minor", type: "waterlogging", notes: `Status: Regular waterlogging during monsoon season | Source: The Tribune reporting` },
  { areaName: `Heritage Street (walled city)`, lat: 31.6226452, lng: 74.8795169, severity: "impassable", type: "waterlogging", notes: `Status: Heavy waterlogging in the inner-city heritage area | Source: The Tribune reporting` },
  { areaName: `Katra Jaimal Singh Road`, lat: 31.6261712, lng: 74.8748354, severity: "impassable", type: "waterlogging", notes: `Status: Heavy waterlogging in the inner-city area | Source: The Tribune reporting` },
  { areaName: `Kachari Square`, lat: 25.335571, lng: 82.985664, severity: "minor", type: "waterlogging", notes: `Status: Inspected as a sensitive low-lying spot during heavy rain, Aug 2026 | Source: ANI / Asianet Newsable reporting, Aug 2026` },
  { areaName: `Pandeypur Square`, lat: 25.3528525, lng: 82.9971909, severity: "minor", type: "waterlogging", notes: `Status: Inspected as a sensitive low-lying spot during heavy rain, Aug 2026 | Source: ANI / Asianet Newsable reporting, Aug 2026` },
  { areaName: `Chowkaghat`, lat: 25.3322933, lng: 82.9904267, severity: "minor", type: "waterlogging", notes: `Status: Inspected as a sensitive low-lying spot; drained within hours using pumps | Source: ANI / Asianet Newsable reporting, Aug 2026` },
  { areaName: `Sigra Square`, lat: 25.3077933, lng: 82.9850552, severity: "minor", type: "waterlogging", notes: `Status: Inspected as a sensitive low-lying spot during heavy rain, Aug 2026 | Source: ANI / Asianet Newsable reporting, Aug 2026` },
  { areaName: `Rathyatra Square`, lat: 25.3060708, lng: 82.9864553, severity: "minor", type: "waterlogging", notes: `Status: Inspected as a sensitive low-lying spot during heavy rain, Aug 2026 | Source: ANI / Asianet Newsable reporting, Aug 2026` },
  { areaName: `Mahmoorganj`, lat: 25.3047084, lng: 82.9792705, severity: "minor", type: "waterlogging", notes: `Status: Inspected as a sensitive low-lying spot during heavy rain, Aug 2026 | Source: ANI / Asianet Newsable reporting, Aug 2026` },
  { areaName: `Maqbool Alam Road`, lat: 25.3422945, lng: 82.9909187, severity: "minor", type: "waterlogging", notes: `Status: Inspected as a sensitive low-lying spot during heavy rain, Aug 2026 | Source: ANI / Asianet Newsable reporting, Aug 2026` },
  { areaName: `Salarpur (Ganga-side)`, lat: 25.3533518, lng: 83.0388227, severity: "impassable", type: "waterlogging", notes: `Status: Flood-watch locality; Police Commissioner and District Magistrate inspected by NDRF boat from Namo Ghat as the Ganga rose above its warning mark at 2cm/hr | Note: Authorities prepared relocation plans, CCTV at relief centres, and round-the-clock monitoring | Source: The News Mill reporting, Sept 2026` },
  { areaName: `Konia (Ganga-side)`, lat: 25.3368242, lng: 83.0321097, severity: "impassable", type: "waterlogging", notes: `Status: Flood-watch locality inspected by boat as Ganga rose above warning mark | Source: The News Mill reporting, Sept 2026` },
  { areaName: `Chhotu Ram Chowk`, lat: 28.89761, lng: 76.5865349, severity: "impassable", type: "waterlogging", notes: `Status: Up to 2 ft of rainwater has accumulated here in the heart of the city; a low-lying spot near Baba Mastnath School where a pregnant HTET exam candidate once fell into a rainwater-covered open sewer | Source: The Tribune reporting, multiple years incl. Aug 2026` },
  { areaName: `Radio Station Chowk`, lat: 28.8987174, lng: 76.5905414, severity: "difficult", type: "waterlogging", notes: `Status: Vehicles have broken down here during heavy waterlogging | Source: The Tribune reporting` },
  { areaName: `Model Town`, lat: 28.8911265, lng: 76.6131717, severity: "difficult", type: "waterlogging", notes: `Status: Severely inundated during the first heavy monsoon spell of 2026 | Source: The Tribune reporting, Aug 2026` },
  { areaName: `Gohana Adda market`, lat: 28.8999503, lng: 76.5847433, severity: "difficult", type: "waterlogging", notes: `Status: Water entered shops here; market forced to shut during heavy rain | Source: The Tribune reporting` },
  { areaName: `Mal Godam Road`, lat: 28.8948264, lng: 76.5759175, severity: "minor", type: "waterlogging", notes: `Status: One of 16 MC-identified waterlogging-prone locations, with a dedicated drain flagged for special attention | Source: The Tribune reporting` },
  { areaName: `Teen Batti Market`, lat: 19.302225, lng: 73.059295, severity: "impassable", type: "waterlogging", notes: `Status: Bhiwandi's principal wholesale/retail marketplace hit by waist-deep water that paralysed business for hours, despite Rs 2.5 crore spent on pre-monsoon desilting | Source: Free Press Journal, July 3, 2026` },
  { areaName: `Bhiwandi (city-wide contractor warning)`, lat: 19.2898318, lng: 73.0686209, severity: "minor", type: "waterlogging", notes: `Status: Civic chief warned contractors of action if flooding is observed anywhere in the city during monsoon — NOTE: this specific warning was from June 2023, an older but recurring pattern (see Teen Batti entry for a 2026-specific event) | Source: Deccan Herald/PTI, June 23, 2023` },
  { areaName: `Sheetla Mata Road`, lat: 28.4803107, lng: 77.0271518, severity: "impassable", type: "waterlogging", notes: `Status: Topped the list of 28 key waterlogging challenges in Aug 2026; MCG Commissioner called it a particular technical challenge, exploring an STP and improved surface drainage | Source: The Tribune / ANI reporting, 2026` },
  { areaName: `Dundahera`, lat: 28.5134376, lng: 77.0801899, severity: "difficult", type: "waterlogging", notes: `Status: Among the ~30 vulnerable spots flagged across multiple review cycles | Source: The Tribune reporting` },
  { areaName: `Bajghera Road`, lat: 28.5202244, lng: 77.0231507, severity: "difficult", type: "waterlogging", notes: `Status: Among the ~30 vulnerable spots flagged across multiple review cycles | Source: The Tribune reporting` },
  { areaName: `Subhash Chowk`, lat: 28.4286913, lng: 77.0370213, severity: "impassable", type: "waterlogging", notes: `Status: One of 4 key trouble spots marked by MCG after a chaotic monsoon day; earmarked for water-injection wells as a permanent fix | Source: The Tribune reporting, 2026` },
  { areaName: `Rajiv Chowk`, lat: 28.4473686, lng: 77.0261079, severity: "impassable", type: "waterlogging", notes: `Status: One of 4 key trouble spots marked by MCG after a chaotic monsoon day | Source: The Tribune reporting, 2026` },
  { areaName: `Medanta underpass`, lat: 28.4393335, lng: 77.0408295, severity: "impassable", type: "waterlogging", notes: `Status: One of 4 key trouble spots marked by MCG; earmarked for water-injection wells as a permanent fix | Source: The Tribune reporting, 2026` },
  { areaName: `Narsinghpur (Delhi-Jaipur highway stretch)`, lat: 28.4146069, lng: 76.9950503, severity: "minor", type: "waterlogging", notes: `Status: A decade-long chronic hotspot; finally stayed dry in July 2026 after a new drain worked as designed, ending years of vulnerability | Source: The Tribune reporting, July 2026` },
  { areaName: `Sherpur Chowk`, lat: 30.8851294, lng: 75.8870734, severity: "difficult", type: "waterlogging", notes: `Status: Major water accumulation witnessed here in 2026, exposing MC monsoon-preparedness claims | Source: The Tribune reporting, May 2026` },
  { areaName: `Haibowal`, lat: 30.9207254, lng: 75.88099, severity: "difficult", type: "waterlogging", notes: `Status: Major water accumulation witnessed here; rainwater entered dairy premises, causing milching difficulties | Source: The Tribune reporting, 2026` },
  { areaName: `Bharat Nagar Chowk`, lat: 30.9042859, lng: 75.8405539, severity: "difficult", type: "waterlogging", notes: `Status: Major water accumulation witnessed here during 2026 monsoon rains | Source: The Tribune reporting, May 2026` },
  { areaName: `Field Ganj`, lat: 30.9086209, lng: 75.8573897, severity: "difficult", type: "waterlogging", notes: `Status: Major water accumulation witnessed here during 2026 monsoon rains | Source: The Tribune reporting, May 2026` },
  { areaName: `Damoria Bridge`, lat: 30.9200054, lng: 75.8452572, severity: "minor", type: "waterlogging", notes: `Status: People have waded through knee-deep water here; a recurring flashpoint over multiple years of reporting | Source: The Tribune reporting` },
  { areaName: `Chaura Bazar`, lat: 30.915934, lng: 75.8568942, severity: "minor", type: "waterlogging", notes: `Status: One of 142 identified low-lying waterlogging hotspots, in the Old City area | Source: The Tribune reporting, 2026` },
  { areaName: `Mall Road`, lat: 30.908558, lng: 75.8402367, severity: "difficult", type: "waterlogging", notes: `Status: Posh area inundated despite MC desilting claims; up to 2 ft of water reported on the road | Source: The Tribune reporting` },
  { areaName: `Dugri`, lat: 30.8590694, lng: 75.8446802, severity: "minor", type: "waterlogging", notes: `Status: Low-lying area where residents describe garbage and filth floating in stagnant floodwater | Source: The Tribune reporting` },
  { areaName: `Jogeshwari–Vikhroli Link Road (JVLR)`, lat: 19.1246678, lng: 72.8958665, severity: "hazardous", type: "pothole", notes: `Status: Residents describe this as currently having the highest concentration of potholes in the city, with poor instant-fill repairs reappearing after heavy vehicles pass | Source: Free Press Journal reporting, July 2026` },
  { areaName: `Ajoy Mehta Marg (Saki Naka – T2 Airport stretch)`, lat: 19.0961829, lng: 72.8877422, severity: "large", type: "pothole", notes: `Status: Historically one of the city’s most notorious pothole stretches (~100 potholes at its worst); an NGO renamed it after the then-BMC chief in protest | Source: Free Press Journal / PressReader reporting` },
  { areaName: `Hennur Main Road, near Lingarajapuram bridge`, lat: 13.0122094, lng: 77.625782, severity: "hazardous", type: "pothole", notes: `Status: A 19-year-old medical student died here in 2021 after a civic body truck hit her scooter as she tried to avoid a pothole | Source: The News Minute investigation` },
  { areaName: `Magadi Road, Anjana Nagar`, lat: 12.9864085, lng: 77.4894354, severity: "hazardous", type: "pothole", notes: `Status: A 38-year-old teacher died here in Jan 2022 after losing control avoiding a pothole and being run over | Source: The News Minute investigation` },
  { areaName: `Mysuru Road, Pantharapalya`, lat: 12.9411992, lng: 77.5246935, severity: "hazardous", type: "pothole", notes: `Status: A 47-year-old woman died here after falling off a bike pillion into the path of a truck; Lokayukta took suo motu action against BBMP over this and two other deaths in the same week | Source: Deccan Herald reporting` },
  { areaName: `Mehrauli-Badarpur Road`, lat: 28.512059, lng: 77.2454531, severity: "hazardous", type: "pothole", notes: `Status: A 37-year-old man died here in March 2025 after his bike hit a pothole hidden under a water-filled patch | Source: The Tribune ground report` },
  { areaName: `Dwarka, Sector 10`, lat: 28.5849492, lng: 77.0582844, severity: "large", type: "pothole", notes: `Status: Broken, pockmarked road right next to the Central Chief Labour Commissioner’s office building | Source: The Tribune ground report` },
  { areaName: `New Friends Colony`, lat: 28.5674621, lng: 77.2691326, severity: "large", type: "pothole", notes: `Status: Cratered roads persist even in this posh locality | Source: The Tribune ground report` },
  { areaName: `Najafgarh`, lat: 28.60903, lng: 76.985358, severity: "large", type: "pothole", notes: `Status: Potholes and broken roads described as a grim constant in this South-West Delhi area | Source: The Tribune ground report` },
  { areaName: `Vikaspuri–Janakpuri stretch`, lat: 28.6386438, lng: 77.07206, severity: "large", type: "pothole", notes: `Status: Residents describe potholes throughout, with no smooth patch left | Source: The Tribune ground report` },
  { areaName: `Nazira, Sivasagar district`, lat: 26.9006575, lng: 94.7225793, severity: "impassable", type: "waterlogging", notes: `Status: Worst single-locality death toll in the disaster: 29 of Sivasagar’s 48 flood deaths occurred here | Source: NDTV, Aug 5, 2026 (citing official sources)` },
  { areaName: `Sivasagar town/district`, lat: 26.989087, lng: 94.639424, severity: "impassable", type: "waterlogging", notes: `Status: District recorded 48 flood deaths, the highest concentration in the disaster | Source: NDTV, Aug 5, 2026` },
  { areaName: `Charaideo district`, lat: 26.9413085, lng: 94.8759751, severity: "impassable", type: "waterlogging", notes: `Status: 29 people swept away by floods here per official sources; named the worst-hit district in an earlier WION report (631 villages inundated across 6 districts) | Source: NDTV, Aug 5, 2026; WION, July 28, 2026` },
  { areaName: `Golaghat district`, lat: 26.5238515, lng: 93.962337, severity: "impassable", type: "waterlogging", notes: `Status: On high alert as the Doyang dam released water and rivers stayed swollen; ultimately the worst-hit district by the final Aug 2026 tally | Source: The Assam Tribune, July 23, 2026` },
  { areaName: `Mahmora (Disang embankment breach)`, lat: 26.9177061, lng: 94.7563797, severity: "difficult", type: "waterlogging", notes: `Status: A Disang river embankment breach here inundated 70–80 villages; residents took shelter on roadsides | Source: India Today NE, July 22, 2026` },
  { areaName: `Simaluguri Junction`, lat: 26.9177061, lng: 94.7563797, severity: "difficult", type: "waterlogging", notes: `Status: Indian Railways suspended train operations through this station due to flooding | Source: The Indian Express, July 20, 2026` },
  { areaName: `Udalguri`, lat: 26.7451087, lng: 92.095914, severity: "difficult", type: "waterlogging", notes: `Status: A key bridge was swept away here, cutting off access to Kathpuri village and leaving many residents stranded | Source: Wikipedia “2026 Assam floods”, citing NDTV, Aug 6, 2026` },
  { areaName: `Jorhat district`, lat: 26.7509207, lng: 94.2036696, severity: "difficult", type: "waterlogging", notes: `Status: Among the first districts hit as flooding spread from Sivasagar/Golaghat before reaching Dibrugarh, Tinsukia, Dhemaji and Majuli | Source: The Hindu, July 25, 2026` },
];

async function seed() {
  await connectDB();

  let created = 0;
  let updated = 0;
  let failed = 0;

  for (const spot of NATIONWIDE_SEED) {
    // Match on rounded coordinates so re-running this script updates the
    // same seed marker instead of piling up duplicates every time.
    const filter = {
      type: spot.type,
      source: "seed",
      "location.lat": { $gte: spot.lat - 0.0005, $lte: spot.lat + 0.0005 },
      "location.lng": { $gte: spot.lng - 0.0005, $lte: spot.lng + 0.0005 },
    };

    const update = {
      type: spot.type,
      source: "seed",
      severity: spot.severity,
      notes: spot.notes,
      reportedBy: "seed-data",
      location: { lat: spot.lat, lng: spot.lng, areaName: spot.areaName },
      // Set explicitly rather than relying on the schema default: during a
      // findOneAndUpdate upsert, Mongoose's setDefaultsOnInsert resolves
      // function defaults without a bound document, so `this.type` isn't
      // reliably available there.
      expiresAt: new Date(
        Date.now() + (spot.type === "pothole" ? 90 : 90) * 24 * 60 * 60 * 1000
      ),
    };

    try {
      const result = await Report.findOneAndUpdate(filter, update, {
        upsert: true,
        new: true,
        setDefaultsOnInsert: true,
        rawResult: true,
      });
      if (result.lastErrorObject?.updatedExisting) updated++;
      else created++;
    } catch (err) {
      failed++;
      console.error(`Failed to seed "${spot.areaName}":`, err.message);
    }
  }

  console.log(
    `Nationwide seed complete: ${created} created, ${updated} updated, ${failed} failed.`
  );
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("Nationwide seed failed:", err);
  process.exit(1);
});